### ISSUE TITLE
error node-sass@4.13.0 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by ManurajKannanth** [ManurajKannanth/ManuTest#1]
28010 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\react-scripts\node_modules\fsevents):
28011 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
28012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
28012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
28012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
28012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
28013 warn eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
28014 warn react-idle@3.0.0 requires a peer of react@15.x but none is installed. You must install peer dependencies yourself.
28015 warn @spm/universal-access-starter-pack@2.5.0 No repository field.
28016 warn @spm/universal-access-starter-pack@2.5.0 No license field.
28017 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
28018 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
28019 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
28019 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
28019 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
28019 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
28020 verbose stack Error: node-sass@4.13.0 postinstall: `node scripts/build.js`
28020 verbose stack Exit status 1
28020 verbose stack     at EventEmitter.<anonymous> (D:\apps\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
28020 verbose stack     at EventEmitter.emit (events.js:193:13)
28020 verbose stack     at ChildProcess.<anonymous> (D:\apps\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
28020 verbose stack     at ChildProcess.emit (events.js:193:13)
28020 verbose stack     at maybeClose (internal/child_process.js:999:16)
28020 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
28021 verbose pkgid node-sass@4.13.0
28022 verbose cwd D:\ReactDev\IBMRESPONSIVEUA7.0.9.0\responsive-ua-app
28023 verbose Windows_NT 10.0.18362
28024 verbose argv "D:\\apps\\nodejs\\node.exe" "D:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
28025 verbose node v11.14.0
28026 verbose npm  v6.7.0
28027 error code ELIFECYCLE
28028 error errno 1
28029 error node-sass@4.13.0 postinstall: `node scripts/build.js`
28029 error Exit status 1
28030 error Failed at the node-sass@4.13.0 postinstall script.
28030 error This is probably not a problem with npm. There is likely additional logging output above.
28031 verbose exit [ 1, true ]

Let me know what is the issue here

**Comment by AlirezaEbrahimkhani** [comment]
try this it works for me 
`npm install node-sass`
`npm install --ignore-scripts`
`bower install`
`npm install`

or this 
`npm install node-sass@latest`
